---
title: "R, u, f"
author: "Natalie Chong"
date: "7/13/2020"
output: html_document
---

```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts
a <- 1.747721

fun <- function(u_m){(((u_m)*R)/((a)+R))}
```

# Records change in resource. mutset1.8 = resource.
```{r}
mutset1.8 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.8)){
u_m <-  as.numeric(rownames(mutset1.8)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 for(j in 1: ncol(mutset1.8)){
    u_n <- as.numeric(colnames(mutset1.8)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
    
   mutset1.8[[i,j]] <- R  
   
 
  

  }
 }
}
```

# Records resident fidelity. mutset1.30 = f
```{r}
mutset1.30 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.30)){
u_m <-  as.numeric(rownames(mutset1.30)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 for(j in 1: ncol(mutset1.30)){
    u_n <- as.numeric(colnames(mutset1.30)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
    
   mutset1.30[[i,j]] <- fun(u_m)  
   

  

  }
 }
}
```

```{r}
plot(x= mutset1.8, y= mutset1.30, xlab = 'Resource Abundance', ylab = 'Plant fidelity', lwd=2,las=3)
```


# Mutant fidelity would yield the same graph.

# Next chunk records uptake rate: mutset1.40 = u
```{r}
mutset1.40 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.40)){
u_m <-  as.numeric(rownames(mutset1.40)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 for(j in 1: ncol(mutset1.40)){
    u_n <- as.numeric(colnames(mutset1.40)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
    
   mutset1.40[[i,j]] <- u_m 
   

  max(mutset1.30)

  }
 }
}
```

# Fidelity as a function of uptake rate! max fidelity is 0.3560578.
```{r}
plot(x = mutset1.40, y = mutset1.30, xlab = "Uptake Rate", ylab = "Plant Fidelity", lwd = 2, las = 3)
```

```{r}
print(mutset1.30)
```

