---
title: "Model_modi"
author: "Natalie Chong"
date: "7/20/2020"
output: html_document
---

#Part 1:  Incoorporating saturating functions in other parts of the host equation to see what happens. Built upon modification(in fidelity) made in Satfunc2.0
```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts
a <- 1.747721 # Resource's half-saturation constant.

fun <- function(u_m,R){(((u_m)*R)/((a)+R))}
r0 <- function(u_m, R, M, H){((u_m)*R*M)/(H*(a + (u_m*R*M/H)))}
r <- function(u_m, u_n, R, N, M){((u_m*M*R) + (u_n*R*N))/((H)*(a + ((u_m*R*M)/H) + ((u_n*R*N)/H)))}
```

# Finished running after 47.15
```{r}
mutset3.0 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) 
dt <- 0.01

for(i in 1:nrow(mutset3.0)){ 
u_m <-  as.numeric(rownames(mutset3.0)[i]) 
   
#Setting initial conditions (letting ecological dynamics play out)   
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - r0(u_m, R, M, H)+ (s*H)/c)*dt
    dH <- (c*r0(u_m, R, M, H)*H  - (s*H) - ((fun(u_m,R)*C_a) + C_c)*M*H  )*dt #host can't exist without already being in the system!
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m,R)*C_a))*H*M - l*M)*dt
  
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
# Save end values to holding vector.
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0

 dt <- 0.01
    
 for(j in 1: ncol(mutset3.0)){
    u_n <- as.numeric(colnames(mutset3.0)[j]) 
   
  delta <- 0.99
  numberofreps <- 0 
  
  N <- .01*M_i 
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - (r(u_m, u_n, R, N, M)) + (s*H)/c)*dt
    dH <- (c*r(u_m, u_n, R, N, M)*H - (s*H) - ((fun(u_m,R)*C_a) + C_c)*M*H - (C_c + fun(u_n, R)*C_a)*N*H )*dt #Host can't multiply in numbers if there were no hosts to begin with.
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m,R)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n,R)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    if(is.na(delta)){print("delta is not a number"); print(N); print (M)}
if(is.na(numberofreps)){print("#ofreps is not a number")} 
  }
  
   mutset3.0[[i,j]] <- delta  
   
   
   if (delta >= 0.995){  mutset3.0[[i,j]] <- 1  }
   if(delta <= 0.005){mutset3.0[[i,j]] <- 0  }
   } 
 
}
 
  print(round(mutset3.0, 3))
  
   library('plot.matrix')
  Mutant_percentage<-mutset3.0
 par(mar = c(4,4,4,4))
  plot(Mutant_percentage, border= NA, fmt.cell='%.3f', fmt.key ="%.3f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') ) 

```

# Code to visualize changes in host abundance,
```{r}
mutset3.1 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20)))
dt <- 0.01

for(i in 1:nrow(mutset3.1)){ #mutset1.6: records every individual who won. nrow here is analogous to "length" command.
u_m <-  as.numeric(rownames(mutset3.1)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10
#N.simu1 <- NaN*tset; N.simu1[1] <- 0


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  #  N <- N.simu1[k-1]
   # f <- 0.5/2 + 0.5*(u_res*M/(u_res*M + u_n*N))
   
    
    dR <- (D*(R_0 - R) - r0(u_m, R, M, H)+ (s*H)/c)*dt
    dH <- (c*r0(u_m, R, M, H)*H  - (s*H) - ((fun(u_m,R)*C_a) + C_c)*M*H  )*dt #host can't exist without already being in the system!
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m,R)*C_a))*H*M - l*M)*dt
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    #N.simu1[k] <- N + dN
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]
#N_i <- N.simu1[length(tset)]

#H0 ; R0 ; M_i ; N_i
 H <- H0
 M <- M_i
 R <- R0
 #N <- N_i
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 for(j in 1: ncol(mutset3.1)){
    u_n <- as.numeric(colnames(mutset3.1)[j])
    delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
   while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - (r(u_m, u_n, R, N, M)) + (s*H)/c)*dt
    dH <- (c*r(u_m, u_n, R, N, M)*H - (s*H) - ((fun(u_m,R)*C_a) + C_c)*M*H - (C_c + fun(u_n, R)*C_a)*N*H )*dt #Host can't multiply in numbers if there were no hosts to begin with.
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m,R)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n,R)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
   }
    mutset3.1[[i,j]] <- H  
    
 }
}

 library(plot.matrix)
 Host_ab_3.0<- mutset3.1 
 par(mar = c(4,4,4,4))
 plot(Host_ab_3.0,border= NA, fmt.key ="%.2f", fmt.cell = "%.3f", xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m") #col = c('mediumpurple4','mediumorchid4','mediumpurple3','mediumpurple','mediumpurple2','mediumpurple1','mediumorchid3','mediumorchid1')) ,breaks = c(1.729, 1.74,1.75,1.76,1.77,1.78,1.79,1.8,1.82)

```

# Part 2: Using initial mutant growth rate to do this
```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts
a <- 1.747721
fun <- function(u_m){(((u_m)*R)/((a)+R))}
r0 <- function(u_m){((u_m)*R*M)/(H*(k + (u_m*R*M/H)))}
r <- function(u_m){((u_m*M*R) + (u_n*R*N))/((H)*(k + ((u_m*R*M)/H) + ((u_n*R*N)/H)))}
```

# <30 minutes, mutant cannot invade.
```{r}
mutset3.2 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) 
dt <- 0.01

for(i in 1:nrow(mutset3.2)){ 
u_m <-  as.numeric(rownames(mutset3.2)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
  
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0

 dt <- 0.01
    
 for(j in 1: ncol(mutset3.2)){
    u_n <- as.numeric(colnames(mutset3.2)[j]) 
   
  delta <- 0.99
  numberofreps <- 0 
  
  N <- .01*M_i 
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000){ 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - (((u_m*M*R) + (u_n*R*N))/((H)*(k + ((u_m*R*M)/H) + ((u_n*R*M)/H)))) + (s*H)/c)*dt
    dH <- (c*(((u_m*M*H) + (u_n*R*N))/((H)*(k + ((u_m*R*M)/H) + ((u_n*R*M)/H))))*H - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt #Host can't multiply in numbers if there were no hosts to begin with.
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    N.N3 <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H - l)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    
if(is.na(numberofreps)){print("#ofreps is not a number")} 
  }
  
   mutset3.2[[i,j]] <- N.N3 
   
   
   #if (delta >= 0.995){  mutset3.2[[i,j]] <- 1  }
  # if(delta <= 0.005){mutset3.2[[i,j]] <- 0  }
   } 
 
}
 
 print(round(mutset3.2, 5))
  
   library('plot.matrix')
  Mutant_initial_growth<-mutset3.2
  par(mar = c(4,4,4,4))
  plot(Mutant_initial_growth, border= NA, fmt.cell='%.3f', fmt.key ="%.3f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') ) 

```