---
title: "Testing different k"
author: "Natalie Chong"
date: "7/13/2020"
output: html_document
---

# Doing it by hand - increasing k/"a" by 10% (Overwritten, would have to run again.)
```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts

#a <- 1.747721
a <- 2
fun <- function(u_m){(((u_m)*R)/((a)+R))}
```

```{r}
mutset1.9 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01


for(i in 1:nrow(mutset1.9)){
u_m <-  as.numeric(rownames(mutset1.9)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 
   
 for(j in 1: ncol(mutset1.9)){
    u_n <- as.numeric(colnames(mutset1.9)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
  
  }
  
   mutset1.9[[i,j]] <- delta
  if (delta >= 0.995){  mutset1.9[[i,j]] <- 1  }
   if(delta <= 0.005){mutset1.9[[i,j]] <- 0  }
 }
}

Inc_k_by_10<- mutset1.9

library(plot.matrix)
par(mar =c(5,5,5,5))
plot(Inc_k_by_10, border= NA, fmt.cell='%.2f', fmt.key ="%.2f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') )
```


# Host Reacts 
```{r}
mutset1.24 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.24)){ 
u_m <-  as.numeric(rownames(mutset1.24)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10
#N.simu1 <- NaN*tset; N.simu1[1] <- 0


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  #  N <- N.simu1[k-1]
   # f <- 0.5/2 + 0.5*(u_res*M/(u_res*M + u_n*N))
   
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    #N.simu1[k] <- N + dN
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]
#N_i <- N.simu1[length(tset)]

#H0 ; R0 ; M_i ; N_i
 H <- H0
 M <- M_i
 R <- R0
 #N <- N_i
 dt <- 0.01
     
 # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
 for(j in 1: ncol(mutset1.24)){
    u_n <- as.numeric(colnames(mutset1.24)[j]) 
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
 
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H)*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + ((fun(u_m)*C_a)))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
   # if(is.na(delta)){print("delta is not a number"); print(N); print (M)}
#if(is.na(numberofreps)){print("#ofreps is not a number")} #1st:maybe step size is too large - dt. Check with is.na function. 
    # 2nd: have possibility of coexistance. 
  
  }
 # if(delta < 0.995 && delta > 0.005){print("delta is intermediate")
 #print(u_m)
  #print(u_n)
 #}
   mutset1.24[[i,j]] <- H  
 }
}
   
 library(plot.matrix)
 HosInc_k_by_10<- mutset1.24 
 par(mar= c(5,5,5,5))
 plot(HosInc_k_by_10,border= NA, fmt.key ="%.2f", fmt.cell = "%.3f", xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m") #breaks = c(1.729, 1.74,1.75,1.76,1.77,1.78,1.79,1.8,1.82), col = c('mediumpurple4','mediumorchid4','mediumpurple3','mediumpurple','mediumpurple2','mediumpurple1','mediumorchid3','mediumorchid1'))
```

# Decreasing k by 10%.
```{r}

D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts

#a <- 1.747721
a <- 1.575
fun <- function(u_m){(((u_m)*R)/((a)+R))}
```

```{r}
mutset1.10 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) 

dt <- 0.01


for(i in 1:nrow(mutset1.10)){
u_m <-  as.numeric(rownames(mutset1.10)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 
   
 for(j in 1: ncol(mutset1.10)){
    u_n <- as.numeric(colnames(mutset1.10)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
  
  }
  
   mutset1.10[[i,j]] <- delta
  if (delta >= 0.995){  mutset1.10[[i,j]] <- 1  }
   if(delta <= 0.005){mutset1.10[[i,j]] <- 0  }
 }
}

Dec_k_by_10<- mutset1.10

library(plot.matrix)
par(mar =c(5,5,5,5))
plot(Dec_k_by_10, border= NA, fmt.cell='%.2f', fmt.key ="%.2f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') )
```

```{r}
mutset1.25 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.25)){ 
u_m <-  as.numeric(rownames(mutset1.25)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10
#N.simu1 <- NaN*tset; N.simu1[1] <- 0


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  #  N <- N.simu1[k-1]
   # f <- 0.5/2 + 0.5*(u_res*M/(u_res*M + u_n*N))
   
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    #N.simu1[k] <- N + dN
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]
#N_i <- N.simu1[length(tset)]

#H0 ; R0 ; M_i ; N_i
 H <- H0
 M <- M_i
 R <- R0
 #N <- N_i
 dt <- 0.01
     
 # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
 for(j in 1: ncol(mutset1.25)){
    u_n <- as.numeric(colnames(mutset1.25)[j]) 
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
 
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H)*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + ((fun(u_m)*C_a)))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
   # if(is.na(delta)){print("delta is not a number"); print(N); print (M)}
#if(is.na(numberofreps)){print("#ofreps is not a number")} #1st:maybe step size is too large - dt. Check with is.na function. 
    # 2nd: have possibility of coexistance. 
  
  }
 # if(delta < 0.995 && delta > 0.005){print("delta is intermediate")
 #print(u_m)
  #print(u_n)
 #}
   mutset1.25[[i,j]] <- H  
 }
}
   
 library(plot.matrix)
 HosDec_k_by_10<- mutset1.25 
 par(mar= c(5,5,5,5))
 plot(HosDec_k_by_10,border= NA, fmt.key ="%.2f", fmt.cell = "%.3f", xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m") 
```



# Increase k by 50%
```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts

#a <- 1.747721
a <- 2.622
fun <- function(u_m){(((u_m)*R)/((a)+R))}
```

```{r}
mutset1.11 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) 

dt <- 0.01


for(i in 1:nrow(mutset1.11)){
u_m <-  as.numeric(rownames(mutset1.11)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 
   
 for(j in 1: ncol(mutset1.11)){
    u_n <- as.numeric(colnames(mutset1.11)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
  
  }
  
   mutset1.11[[i,j]] <- delta
  if (delta >= 0.995){  mutset1.11[[i,j]] <- 1  }
   if(delta <= 0.005){mutset1.11[[i,j]] <- 0  }
 }
}

Inc_k_by_50<- mutset1.11

library(plot.matrix)
par(mar =c(5,5,5,5))
plot(Inc_k_by_50, border= NA, fmt.cell='%.2f', fmt.key ="%.2f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') )
```

# Host Reacts
```{r}
mutset1.26 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.26)){ 
u_m <-  as.numeric(rownames(mutset1.26)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10
#N.simu1 <- NaN*tset; N.simu1[1] <- 0


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  #  N <- N.simu1[k-1]
   # f <- 0.5/2 + 0.5*(u_res*M/(u_res*M + u_n*N))
   
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    #N.simu1[k] <- N + dN
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]
#N_i <- N.simu1[length(tset)]

#H0 ; R0 ; M_i ; N_i
 H <- H0
 M <- M_i
 R <- R0
 #N <- N_i
 dt <- 0.01
     
 # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
 for(j in 1: ncol(mutset1.26)){
    u_n <- as.numeric(colnames(mutset1.26)[j]) 
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
 
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H)*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + ((fun(u_m)*C_a)))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
  
  }

   mutset1.26[[i,j]] <- H  
 }
}
   
 library(plot.matrix)
 HosInc_k_by_50<- mutset1.26 
 par(mar= c(5,5,5,5))
 plot(HosInc_k_by_50,border= NA, fmt.key ="%.2f", fmt.cell = "%.3f", xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m") 
```

# Decrease k by 50% 
```{r}
D <- 0.5 # Dilution Rate (Outflow)
R_0 <- 25 # Inflow Concentration (Nitrogen)
l <- 0.05 # fungal mortality
s <- 0.05 # senescence coefficient
c <- 0.7 # host's C:N Ratio
b <- 0.3 #symbiont's intrinsic growth rate
C_a <- 0.2 #Allocation Carbon
C_c <- 0.3 #Construction Carbon 
v <- 0.3  #Conversion efficiency, Host carbon to more symbionts

#a <- 1.747721
a <- 0.8739
fun <- function(u_m){(((u_m)*R)/((a)+R))}
```

```{r}
mutset1.12 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) 

dt <- 0.01


for(i in 1:nrow(mutset1.12)){
u_m <-  as.numeric(rownames(mutset1.12)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10



for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
   
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]

 H <- H0
 M <- M_i
 R <- R0
 
 dt <- 0.01
      #added equilibrated resident population size. starting from **
 
   
 for(j in 1: ncol(mutset1.12)){
    u_n <- as.numeric(colnames(mutset1.12)[j]) # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
   
    
   
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
  
 #simulates dynamics initial.
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
  
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
    
  
  }
  
   mutset1.12[[i,j]] <- delta
  if (delta >= 0.995){  mutset1.12[[i,j]] <- 1  }
   if(delta <= 0.005){mutset1.12[[i,j]] <- 0  }
 }
}

Dec_k_by_50<- mutset1.12

library(plot.matrix)
par(mar =c(5,5,5,5))
plot(Dec_k_by_50, border= NA, fmt.cell='%.2f', fmt.key ="%.2f", breaks = c(-0.1,0.011,.99,1),xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m", col = c('white','grey','black') )
```




```{r}
mutset1.23 <- matrix(NaN,nrow = 20, ncol = 20, dimnames = list(seq(1/20, 1, 1/20), seq(1/20, 1, 1/20))) #name rows to be u_m ; cols to be u_n. made a matrix thingie yay

dt <- 0.01

for(i in 1:nrow(mutset1.23)){ 
u_m <-  as.numeric(rownames(mutset1.23)[i]) 
   
#**    
tset <- seq(from=0, to= 300, length.out = 10000)
H.simu1 <- NaN*tset; H.simu1[1] <- 1
M.simu1 <- NaN*tset; M.simu1[1] <- 1
R.simu1 <- NaN*tset; R.simu1[1] <- 10
#N.simu1 <- NaN*tset; N.simu1[1] <- 0


for(k in 2:length(tset)){
    dt <- tset[k] - tset[k-1] 
    H <- H.simu1[k-1] 
    M <- M.simu1[k-1]
    R <- R.simu1[k-1]
  #  N <- N.simu1[k-1]
   # f <- 0.5/2 + 0.5*(u_res*M/(u_res*M + u_n*N))
   
    
    dR <- (D*(R_0 - R) - u_m*M*R+ (s*H)/c)*dt
    dH <- (c*u_m*R*M  - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H  )*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + (fun(u_m)*C_a))*H*M - l*M)*dt
    
    H.simu1[k] <- H + dH
    M.simu1[k] <- M + dM
    #N.simu1[k] <- N + dN
    R.simu1[k] <- R + dR
    
}
H0 <- H.simu1[length(tset)]
R0 <- R.simu1[length(tset)]
M_i <- M.simu1[length(tset)]
#N_i <- N.simu1[length(tset)]

#H0 ; R0 ; M_i ; N_i
 H <- H0
 M <- M_i
 R <- R0
 #N <- N_i
 dt <- 0.01
     
 # do whole while loop, initialize u_n and u_m to actual numbers, store delta in the matrix. 
 for(j in 1: ncol(mutset1.23)){
    u_n <- as.numeric(colnames(mutset1.23)[j]) 
  delta <- 0.99 # mutant percentage in the population  
  numberofreps <- 0 
 
  N <- .01*M_i #change according to what the resident equilibrates to..
  M <- .99*M_i
  H <- H0
  R <- R0
 
  
  while(numberofreps < 1000000 && (delta < 0.995 && delta > 0.005)){ # && means and, if previous is not true then won't run second. Other criteria: mutant declines, if delta is greater than 99.5% or less than .5%. Simulates dynamics. 
    numberofreps <- numberofreps + 1; 
    
    dR <- (D*(R_0 - R) - u_m*M*R - u_n*N*R + (s*H)/c)*dt
    dH <- (c*u_m*R*M + c*u_n*R*N - (s*H) - ((fun(u_m)*C_a) + C_c)*M*H - (C_c + fun(u_n)*C_a)*N*H)*dt
    dM <- (b*(1-(u_m/6))*v*(C_c + ((fun(u_m)*C_a)))*H*M - l*M)*dt
    dN <- (b*(1-(u_n/6))*v*(C_c + (fun(u_n)*C_a))*H*N - l*N)*dt
    
    H <- H + dH
    M <- M + dM
    N<- N + dN
    R<- R + dR
    delta <- N / (N+M)
   # if(is.na(delta)){print("delta is not a number"); print(N); print (M)}
#if(is.na(numberofreps)){print("#ofreps is not a number")} #1st:maybe step size is too large - dt. Check with is.na function. 
    # 2nd: have possibility of coexistance. 
  
  }
 # if(delta < 0.995 && delta > 0.005){print("delta is intermediate")
 #print(u_m)
  #print(u_n)
 #}
   mutset1.23[[i,j]] <- H  
 }
}
   
 library(plot.matrix)
 HosDec_k_by_50<- mutset1.23
 par(mar = c(5,5,5,5))
 plot(HosDec_k_by_50,border= NA, fmt.key ="%.3f", fmt.cell = "%.3f", xlab= "Mutant Uptake Rate, u_n", ylab = "Resident Uptake Rate, u_m") #breaks = c(1.729, 1.74,1.75,1.76,1.77,1.78,1.79,1.8,1.82), col = c('mediumpurple4','mediumorchid4','mediumpurple3','mediumpurple','mediumpurple2','mediumpurple1','mediumorchid3','mediumorchid1'))
```

